### ISSUE TITLE
Persistence of variables when executing separate exec calls

### ISSUE THREAD

**Issue by carlosuc3m** [apposed/appose#9]
Currently Appose is not able to access the variables that where created in the same Python Service on previous Tasks.
This means that if we do:

```java
Environment env = new Environment() {
			@Override public String base() { return envPath; }
			@Override public boolean useSystemPath() { return false; }
			};
Service python = env.python();

Task task1 = python.task("a=5")
task1.waitFor()
Task task2 = python.task("a + a")
task2.waitFor()
```

I will get an error saying that the variable a is not defined
```
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined
```
The error is caused by the following line:
https://github.com/apposed/appose-python/blob/ed37c651084601d201e7dc7c8e8bb5b5f72e0d70/src/appose/python_worker.py#L108

This line is setting the globals to be empty, that is that there are no global variables defined for the Python code that is going to be executed. That line should be:
```python
_globals = None
```
Which instead is interpreted as that we are not setting any global variables in the scope.

To test the behaviour try the following:
```python
exec("a=5", None, None)
exec("print(a)", None, None)
```
Output:
```
5
```

and compare to:
```
exec("a=5", {}, {})
exec("print(a)", {}, {})
```
Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>

```

However, weirdly, in Appose in order to get this to work, the variables created in one task need to be set explicitly as a global variable to be accessible in other tasks.
```python
globals()['np'] = np
```

**Comment by carlosuc3m** [comment]
I think that I understand it now.
Setting globals to None basically what it says is that there is no global variables "dictionary", so any variable created is saved to the locals dictionary of variables.
Example:
```
exec("a = 5\nprint(str(locals()))", None, {'b':7})
```
Output:
```
{'b': 7, 'a': 5}
```

This is why if we call now in another `exec` the variables previously created setting a new locals dictionary, the previous variables will be overwritten, as they were set up in the local namespace.
```
exec("print(a)", None, {'b':7})
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined
```
Output:
```
{'b': 7, 'a': 5}
```

This is exactly what is done in the Python part, the local variables are constantly rewritten each time `exec` is called and there is no global variables becauuse if we use ` _globals = {}`  the global namespace is set to an empty dictionary everytime and if we set it to ` _globals = None`, the global scope is not created and every variable is saved in the local namespace, which is rewritten everytime the user calls a Python task.

This is why if when we first execute a task we, create the globals dictionary by for example doing:
```
globals()['np'] = np
```
the variables will be saved in the global scope and, unless the global scope is rewritten in the next tasks, they will be accessible in the next `exec` call.
Example:
```
exec("a = 5\nglobals()['a'] = a", None, {'b':7})
exec("print(a)", None, {'b':9})
```
Output:
```
5
```

Another way to do it is by creating the globals dictionary the first time `exec` is called. That way the variables created can be added to the global scope and called in subsequent `exec` calls by setting globals to `None`.
Example:
```
exec("a = 5", {}, {'b':7})
exec("print(a)", None, {'b':9})
```
Output:
```
5
```

**Comment by carlosuc3m** [comment]
Hello, I deleted my previous comment because it was completely wrong, I had not understood anything.

After reading the docs (probaly I should have done it way earlier) I realised that setting both globals and locals is equivalent to inserting the piece of code in the script. It basically makes the code in the script share locals and globals with the program the exec is embedded in.
This is why if we do: 

```
exec("a=5", None, None)
exec("print(a)", None, None)
```
It works.

However, whenever we set globals or locals, it will not work anymore, because now the exec has its own variables.
In addition if we do the following:
```
>>> _globals = {}
>>> _locals = {}
>>> exec("a=5", _globals, _locals)
>>> exec("print(a)", _globals, _locals)
5
>>> _locals
{'a': 5}
```

It seems that the new variables created in the scope of exec are added to the globals locals dictionary and not the globals. We still can add the to the globals by doing ` globals()["a"] = a`.

With this in mind I think it might make sense to keep track of the globals and locals as attributes of the python service to guarantee variable consistency among tasks.

What do you think?

**Comment by ctrueden** [comment]
Current plan is for task scripts to be able to use a `task.shared` dictionary to save variables, which will then automatically be added to the locals of subsequent tasks. (So reading from `task.shared` will rarely if ever be necessary—only writing to it for persistence beyond the current task.)

**Comment by ctrueden** [comment]
I pushed a `common-state` branch with [this commit](https://github.com/apposed/appose-python/commit/a66e5ade4c4f516de479be6cc956c5e6ed1973ca) adding a `task.export` function to the appose-python worker API.

In a task, you can now write:
```python
import numpy as np
import matplotlib as plt
task.export(np=np, plt=plt)
```
and then `np` and `plt` will magically be made available for any new tasks that run.

@carlosuc3m @stefanhahmann What do you think? Is this elegant enough?

**Comment by ctrueden** [comment]
I merged the `task.export` work, implemented it for appose-java as well, and released both components at v0.7.0.
